create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  ticket_no bigint generated by default as identity,
  guest_name text,
  guest_id text,
  status text not null default 'queued' check (status in ('queued', 'mixing', 'served', 'cancelled')),
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists guest_id text;

create table if not exists public.recipes (
  drink_id text primary key,
  name_zh text not null,
  name_en text not null,
  ingredients jsonb not null default '[]'::jsonb,
  method text,
  garnish text,
  glass text,
  prep_notes text,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists recipes_set_updated_at on public.recipes;
create trigger recipes_set_updated_at
before update on public.recipes
for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.recipes enable row level security;

grant usage on schema public to anon;
grant insert, select, update, delete on public.orders to anon;
grant select on public.recipes to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "Guests can create orders" on public.orders;
create policy "Guests can create orders"
on public.orders for insert
to anon
with check (true);

drop policy if exists "Simple admin can read orders" on public.orders;
create policy "Simple admin can read orders"
on public.orders for select
to anon
using (true);

drop policy if exists "Simple admin can update order status" on public.orders;
create policy "Simple admin can update order status"
on public.orders for update
to anon
using (true)
with check (status in ('queued', 'mixing', 'served', 'cancelled'));

drop policy if exists "Simple admin can close bar" on public.orders;
create policy "Simple admin can close bar"
on public.orders for delete
to anon
using (true);

drop policy if exists "Recipes are readable by admin UI" on public.recipes;
create policy "Recipes are readable by admin UI"
on public.recipes for select
to anon
using (true);

insert into public.recipes (drink_id, name_zh, name_en, ingredients, method, garnish, glass, prep_notes)
values
  ('whiskey-sour', '威士忌酸', 'Whiskey Sour', '["波本威士忌 60ml", "新鲜柠檬汁 25ml", "糖浆 20ml", "蛋清或消泡剂 optional"]', 'Dry shake 起泡，再加冰 hard shake，滤入杯中。', '柠檬皮或酒渍樱桃', 'Rocks / Coupe', '少甜时糖浆减至 12–15ml；泡沫要细密，不要过度稀释。'),
  ('classic-daiquiri', '经典大吉利', 'Classic Daiquiri', '["白朗姆 60ml", "新鲜青柠汁 25ml", "糖浆 15ml"]', '加冰 shake 至冰冷，双重过滤入冰镇 coupe。', '青柠轮或青柠皮', 'Coupe', '酸甜要干净利落，糖浆不要盖过朗姆的甘蔗香。'),
  ('classic-gimlet', '经典琴蕾', 'Classic Gimlet', '["金酒 60ml", "青柠汁 20ml", "糖浆 15ml"]', '加冰 shake，双重过滤入冰镇 coupe。', '青柠皮', 'Coupe / Nick & Nora', '如果用 lime cordial，可减少糖浆；保持草本和酸感的锋利。'),
  ('white-lady', '白佳人', 'White Lady', '["金酒 45ml", "橙酒 20ml", "柠檬汁 20ml", "蛋清 optional"]', 'Dry shake 后加冰 shake，双重过滤。', '柠檬皮', 'Coupe', '橙香要轻，不要甜腻；有蛋清时口感更丝滑。'),
  ('classic-margarita', '经典玛格丽特', 'Classic Margarita', '["龙舌兰 50ml", "橙酒 20ml", "新鲜青柠汁 25ml", "糖浆 5ml optional"]', '杯口盐边，加冰 shake，过滤入杯。', '盐边与青柠角', 'Margarita / Rocks', '盐边只做半圈更好入口；少甜时不加糖浆。'),
  ('gin-tonic', '金汤力', 'Gin & Tonic', '["金酒 45ml", "冰镇汤力水 120ml", "青柠角"]', '杯中加满冰，倒入金酒，轻轻补汤力水，短暂提拉混合。', '青柠角或黄瓜片', 'Highball', '杯子和汤力水都要冷；气泡是这杯的灵魂。'),
  ('long-island-iced-tea', '长岛冰茶', 'Long Island Iced Tea', '["伏特加 15ml", "金酒 15ml", "白朗姆 15ml", "龙舌兰 15ml", "橙酒 15ml", "柠檬汁 25ml", "糖浆 15ml", "可乐 top"]', '除可乐外加冰 shake，倒入长饮杯，补可乐。', '柠檬片', 'Highball', '后劲强，建议控制稀释和甜度，提醒客人慢慢喝。'),
  ('kamikaze', '神风特攻队', 'Kamikaze', '["伏特加 45ml", "橙酒 20ml", "青柠汁 20ml"]', '加冰 shake 至冰冷，过滤入杯。', '青柠片', 'Coupe / Shot', '口感要冰冷锋利；偏酸时青柠可加到 25ml。'),
  ('old-fashioned', '古典鸡尾酒', 'Old Fashioned', '["波本威士忌 60ml", "糖浆 7.5ml", "Angostura 苦精 2 dash", "橙皮"]', '搅拌杯加冰 stir，滤入大冰块 rocks glass。', '橙皮油与橙皮', 'Rocks', '稀释要稳，橙皮油要擦杯沿；适合慢饮。')
on conflict (drink_id) do update set
  name_zh = excluded.name_zh,
  name_en = excluded.name_en,
  ingredients = excluded.ingredients,
  method = excluded.method,
  garnish = excluded.garnish,
  glass = excluded.glass,
  prep_notes = excluded.prep_notes;
